trigger:
  - none
  # branches:
  #   include:
  #     - main

pool:
  name: Default

steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'