trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: serviceConnection
    displayName: "Azure Service Connection"
    type: string
  - name: serviceConnectionObjectId
    displayName: "Azure Service Connection Object Id"
    type: string
  - name: subscriptionId
    displayName: "Azure Subscription Id"
    type: string

variables:
  TF_VERSION: "1.7.5"

steps:
  - task: Bash@3
    displayName: "Install Terraform"
    inputs:
      targetType: "inline"
      script: |
        echo "Installing Terraform version $(TF_VERSION)..."
        wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
        unzip terraform_$(TF_VERSION)_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform version

  - task: AzureCLI@2
    displayName: "Create terraform storage"
    inputs:
      azureSubscription: "${{ parameters.serviceConnection }}"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      workingDirectory: infra/backend-storage
      inlineScript: |
        az account set --subscription "${{ parameters.subscriptionId }}"
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
        export ARM_USE_OIDC=true
        terraform init
        terraform apply -auto-approve \
          -var="service_connection_object_id=${{ parameters.serviceConnectionObjectId }}" \
          -var="tenant_id=$ARM_TENANT_ID"
